### DISCUSSION TITLE
want to use docker but version 3.5?

### DISCUSSION THREAD

**Discussion by sprappcom** [cortezaproject/corteza-server#1797] [Q&A] [answered]
what is the latest version? i thought it's 2023.9 or something?
can update this?
https://docs.cortezaproject.org/corteza-docs/2023.9/devops-guide/examples/deploy-online/index.html

docker-compose.yaml
```
version: '3.5'

services:
  server:
    image: cortezaproject/corteza:${VERSION}
```
