### ISSUE TITLE
oauth2 invalid redirect uri

### ISSUE THREAD

**Issue by truemerrill** [cortezaproject/corteza-server#162]
**Describe the bug**
Using `corteza-2021.3` I am unable to login after registering the initial (administrator) user.  `docker logs -f corteza_server_1` shows an "invalid redirect uri" error.

**To Reproduce**
Here is my docker-compose.yml.  It's very close to the [minimal example](https://docs.cortezaproject.org/corteza-docs/2021.3/devops-guide/index.html#deploy-offline) provided in the documentation, but with the `/data/server` and `data/db` directories mounted onto their respective containers.

```
version: '3.5'

services:
  server:
    image: cortezaproject/corteza-server:${VERSION}
    restart: on-failure
    env_file: [ .env ]
    depends_on: [ db ]
    ports: [ "127.0.0.1:18080:80" ]
    volumes: [ "./data/server:/data" ]

  db:
    # MySQL Database
    # See https://hub.docker.com/r/percona/percona-server for details
    image: percona:8.0
    restart: on-failure
    volumes: [ "./data/db:/var/lib/mysql" ]
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER:     dbuser
      MYSQL_PASSWORD: dbpass
      # get the random generated password by running: docker-compose logs db | grep "GENERATED ROOT PASSWORD"
      MYSQL_RANDOM_ROOT_PASSWORD: random
    healthcheck: { test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"], timeout: 20s, retries: 10 }
```

Here is the `.env` file

```
########################################################################################################################
# docker-compose supports environment variable interpolation/substitution in compose configuration file
# (more info: https://docs.docker.com/compose/environment-variables)

########################################################################################################################
# General settings
DOMAIN=local.cortezaproject.org:18080
VERSION=2021.3

########################################################################################################################
# Database connection

DB_DSN=dbuser:dbpass@tcp(db:3306)/dbname?collation=utf8mb4_general_ci

########################################################################################################################
# Server settings

# Serve Corteza webapps alongside API
HTTP_WEBAPP_ENABLED=true

# Send action log to container logs as well
# ACTIONLOG_DEBUG=true

# Uncomment for extra debug info if something goes wrong
# LOG_LEVEL=debug

# Use nicer and colorful log instead of JSON
# LOG_DEBUG=true

########################################################################################################################
# Authentication

# Secret to use for JWT token
# Make sure you change it (>30 random characters) if
# you expose your deployment to outside traffic
# AUTH_JWT_SECRET=this-is-only-for-demo-purpose--make-sure-you-change-it-for-production

########################################################################################################################
# SMTP (mail sending) settings

# Point this to your local or external SMTP server if you want to send emails.
# In most cases, Corteza can detect that SMTP is disabled and skips over sending emails without an error
#SMTP_HOST=smtp-server.example.tld:587
#SMTP_USER=postmaster@smtp-server.example.tld
#SMTP_PASS=this-is-your-smtp-password
#SMTP_FROM='"Demo" <info@your-demo.example.tld>'
```

Start the containers with `docker-compose up -d`.  Then open [http://localhost:18080](http://localhost:18080) and create the first user's account.  Instead completing the login after account creation, the user sees a black browser window and the error can be viewed in the logfiles. 

**Expected behavior**
After logging in, the user should be directed to corteza one. 

**Logs**
```
{"level":"error","ts":1617826756.074609,"caller":"oauth2/oauth2.go:95","msg":"invalid redirect uri"}
{"level":"error","ts":1617826765.0259004,"caller":"oauth2/oauth2.go:95","msg":"invalid redirect uri"}
{"level":"error","ts":1617826772.4235597,"caller":"oauth2/oauth2.go:95","msg":"invalid redirect uri"}
{"level":"error","ts":1617826798.8484368,"caller":"oauth2/oauth2.go:95","msg":"invalid redirect uri"}
```
