### ISSUE TITLE
Can't start in kubernetes with corredor enabled

### ISSUE THREAD

**Issue by knewter** [cortezaproject/corteza-server#79]
**Describe the bug**
I've deployed corteza in my kubernetes cluster, but to get it running I had to set `CORREDOR_ENABLED=false`. That's because if I don't do that, I get this error and the server fails to start:

```
Error: CA public key (/certs/corredor/client/ca.crt) not found 
```

**To Reproduce**
I've attached a kubernetes yaml file that (given the mysql database exists, which I provision elsewhere with kubedb) will deploy the service in a way that works. If you remove `CORREDOR_ENABLED=false` it fails to boot with the above-listed error.

**Expected behavior**
I expected the server to boot or to be able to read in the documentation something related to a certificate required to talk to corredor. I also just expected corredor to boot with the rest of the system, but *I have only learned corteza existed yesterday so am well aware that my mental model is likely lacking.*

**Additional context**
I can boot the app and use messaging / administer users / use the jitsi bridge if i disable corredor, but crm and servicecloud don't work, and compose doesn't really work though it will list namespaces and let me create one. I assume these use corredor heavily but again, no real clue.

Here's a kubernetes setup that describes what I'm trying to do at least...

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corteza-server
  namespace: corteza
  labels:
    app: corteza-server
  annotations: {}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: corteza-server
  template:
    metadata:
      labels:
        app: corteza-server
    spec:
      containers:
        - name: corteza-server
          image: cortezaproject/corteza-server:2020.3.0-rc.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: CORREDOR_ENABLED
              value: "false"
            - name: LOG_LEVEL
              value: debug
            - name: LOG_DEBUG
              value: "true"
            - name: VIRTUAL_HOST
              value: api.corteza.dbadbadba.com
            - name: HTTP_CLIENT_TSL_INSECURE
              value: "true"
            - name: PROVISION_SETTINGS_AUTH_FRONTEND_URL_BASE
              value: https://corteza.dbadbadba.com
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: corteza-mysql-auth
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: corteza-mysql-auth
                  key: password
            - name: DB_DSN
              value: "$(MYSQL_USERNAME):$(MYSQL_PASSWORD)@tcp(corteza-mysql:3306)/corteza?collation=utf8mb4_general_ci"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corteza-webapp
  namespace: corteza
  labels:
    app: corteza-webapp
  annotations: {}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: corteza-webapp
  template:
    metadata:
      labels:
        app: corteza-webapp
    spec:
      containers:
        - name: corteza-webapp
          image: cortezaproject/corteza-webapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-webapp
              containerPort: 80
              protocol: TCP
          env:
            - name: API_BASEURL
              value: api.corteza.dbadbadba.com
            - name: VIRTUAL_HOST
              value: corteza.dbadbadba.com
            - name: MONOLITH_API
              value: "true"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: corteza-server
  namespace: corteza
  labels:
    app: corteza-server
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: corteza-server
---
apiVersion: v1
kind: Service
metadata:
  name: corteza-webapp
  namespace: corteza
  labels:
    app: corteza-webapp
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: corteza-webapp
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: corteza-server
  namespace: corteza
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.org/websocket-services: "corteza-server"
spec:
  tls:
    - hosts:
        - api.corteza.dbadbadba.com
      secretName: corteza-server-tls
  rules:
    - host: api.corteza.dbadbadba.com
      http:
        paths:
          - path: /
            backend:
              serviceName: corteza-server
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: corteza-webapp
  namespace: corteza
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - corteza.dbadbadba.com
      secretName: corteza-webapp-tls
  rules:
    - host: corteza.dbadbadba.com
      http:
        paths:
          - path: /
            backend:
              serviceName: corteza-webapp
              servicePort: 80
```
